//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauGia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebDauGiaEntities : DbContext
    {
        public WebDauGiaEntities()
            : base("name=WebDauGiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CommentVendor> CommentVendors { get; set; }
        public virtual DbSet<CommentWinner> CommentWinners { get; set; }
        public virtual DbSet<DeniedProduct> DeniedProducts { get; set; }
        public virtual DbSet<DeniedVendor> DeniedVendors { get; set; }
        public virtual DbSet<HistoryAuction> HistoryAuctions { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WatchList> WatchLists { get; set; }
    }
}
