//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDauGia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.HistoryAuctions = new HashSet<HistoryAuction>();
            this.Photos = new HashSet<Photo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> Price { get; set; }
        public string Descrition { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PriceAuction { get; set; }
        public Nullable<int> TopPrice { get; set; }
        public Nullable<int> Winner { get; set; }
        public Nullable<int> StepPrice { get; set; }
        public Nullable<int> BuyNowPice { get; set; }
        public Nullable<bool> AutoExtend { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryAuction> HistoryAuctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        public virtual User User { get; set; }
    }
}
